name: Publish

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  registry-url: "https://registry.npmjs.org/"

            - name: Install dependencies
              run: npm install

            # if i have tests i will uncomment it
            # - name: Run tests
            #   run: npm test

            - name: Build project
              run: npm run build

            - name: Version and Publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  npx changeset version  # Version packages based on changesets
                  npm publish  # Publish the packages to npm
