name: Publish

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  registry-url: "https://registry.npmjs.org/"

            - name: Install dependencies
              run: npm install

            # Uncomment if you have tests
            # - name: Run tests
            #   run: npm test

            - name: Build project
              run: npm run build

            - name: Version and Publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  npx changeset version  # Version packages based on changesets
                  npm publish  # Publish the packages to npm

            # - name: Get current date
            #   id: date
            #   run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

            # - name: Create GitHub Release
            #   uses: actions/create-release@v1
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   with:
            #       tag_name: v${{ steps.date.outputs.date }}
            #       release_name: Release v${{ steps.date.outputs.date }}
            #       body: |
            #           New release based on changesets.
            #       draft: false
            #       prerelease: false
